version: "3.9"
services:
  postgresql:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: example
      # PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
  # nginx:
  #   image: "nginx:latest"
  #   ports:
  #     - "5000:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - .:/var/www
